name: CI

on: push

jobs:
  pre-package:
    name: Run Lint and Pytest
    if: github.ref != 'refs/heads/develop' && !contains(github.ref, 'release/') && !contains(github.ref, 'tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Run unit tests
        run: make test

      - name: Coverage report
        run: make coverage